Setup another task for refreshing corpus contents.

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -29,6 +29,85 @@ jobs:
           restore-keys: |
             corpus-
             build-
+      - name: Build project
+        uses: ./
+        with:
+          run: |
+            cmake -GNinja -B build -S .
+            python tools/ninja.py build
+      - if: github.ref == 'refs/heads/stable'
+        name: Run corpus
+        uses: ./
+        with:
+          run: |
+            find unit_tests/fuzz/crashes -type f -exec cp '{}' unit_tests/fuzz/corpus ';'
+            while ! ninja -C build -j3 regression-log >/dev/null 2>&1; do
+              find unit_tests/fuzz/corpus | wc -l
+              echo "Regression failed, retrying..."
+            done
+      - name: Corpus merge
+        uses: ./
+        with:
+          run: python tools/corpus_merge.py
+      - name: Corpus trim
+        uses: ./
+        with:
+          run: python tools/corpus_trim.py
+      - name: Run regression
+        uses: ./
+        with:
+          run: ninja -C build -j1 regression
+      - continue-on-error: ${{ github.ref != 'refs/heads/stable' }}
+        uses: stefanzweifel/git-auto-commit-action@v4.16.0
+        with:
+          branch: corpus-${{ github.ref }}/${{ github.run_id }}
+          commit_message: Update fuzzing corpus.
+          create_branch: true
+          file_pattern: unit_tests/fuzz
+          repository: ${{ github.workspace }}
+  debug:
+    concurrency:
+      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
+      group: debug-${{ github.workflow }}-${{ github.ref }}
+    env:
+      CMAKE_BUILD_TYPE: Debug
+      CXXFLAGS: ""
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3.3.0
+        with:
+          submodules: true
+      - name: CCache
+        uses: actions/cache@v3.2.6
+        with:
+          key: debug-${{ github.run_id }}
+          path: .ccache
+          restore-keys: |
+            debug-
+            build-
+      - name: Run regression
+        uses: ./
+        with:
+          run: |
+            cmake -GNinja -B build -S .
+            python tools/ninja.py build check-rand regression
+  gather:
+    concurrency:
+      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
+      group: gather-${{ github.workflow }}-${{ github.ref }}
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3.3.0
+        with:
+          submodules: true
+      - name: CCache
+        uses: actions/cache@v3.2.6
+        with:
+          key: gather-${{ github.run_id }}
+          path: .ccache
+          restore-keys: |
+            gather-
+            build-
       - name: Run regression
         uses: ./
         with:
@@ -65,37 +144,11 @@ jobs:
       - continue-on-error: ${{ github.ref != 'refs/heads/stable' }}
         uses: stefanzweifel/git-auto-commit-action@v4.16.0
         with:
-          branch: regression-${{ github.workflow }}-${{ github.ref }}/${{ github.run_id }}
+          branch: gather-${{ github.ref }}/${{ github.run_id }}
           commit_message: Update fuzzing corpus.
           create_branch: true
           file_pattern: unit_tests/fuzz
           repository: ${{ github.workspace }}
-  debug:
-    concurrency:
-      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
-      group: debug-${{ github.workflow }}-${{ github.ref }}
-    env:
-      CMAKE_BUILD_TYPE: Debug
-      CXXFLAGS: ""
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v3.3.0
-        with:
-          submodules: true
-      - name: CCache
-        uses: actions/cache@v3.2.6
-        with:
-          key: debug-${{ github.run_id }}
-          path: .ccache
-          restore-keys: |
-            debug-
-            build-
-      - name: Run regression
-        uses: ./
-        with:
-          run: |
-            cmake -GNinja -B build -S .
-            python tools/ninja.py build check-rand regression
   libcpp:
     concurrency:
       cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
